defunkt/gist

- bin/gist
- lib/gist.rb
Addressing pagination of gists when listing https://github.com/defunkt/gist/issues/201. Apologies if my use of optparse isn't the best.
/cc @ConradIrwin
> add page option when listing gists

- lib/gist.rb
`taccess_token` => `access_token`.
The wrong query string is preventing authenticated listing, so `--list`
without argument is wrongly listing recent gists on the entire
gist.github.com (instead of listing gists of the authenticated user) in
v4.4.1.
> Fix typo introduced in 687c15a

- bin/gist
Don't try to trap SIGPIPE if you're on a platform that doesn't support it (like
Windows).
> Check for SIGPIPE (closes #209)

- lib/gist.rb
The "--shorten" command line option had stopped working since the
git.io API changed.
1. The endpoint is now "/create".
2. HTTP links result in a 301 redirect.
3. The resulting shortcode is in the response body.
Thanks-To: https://github.com/tjt263 for the hint.
Fixes: https://github.com/defunkt/gist/issues/229
> Fix the "--shorten" option

- README.md
- lib/gist.rb
Replace https://github.com/settings/applications with https://github.com/settings/tokens
Suggested-By: https://github.com/starius
Completes: https://github.com/defunkt/gist/issues/225
> Print GitHub tokens URL on OAuth completion

- lib/gist.rb
- spec/shorten_spec.rb
1. Retain a test for the older 201 response but use https.
2. Add a test for the 200 response that git.io currently returns.
Updates: https://github.com/defunkt/gist/pull/240
> Update the tests for the shorten command

- bin/gist
- lib/gist.rb
Simple feature requested in #211.
You can delete the gist with the ID or URL using `gist --delete [ ID | URL ]` and you must be logged in.
> Add --delete option

- Rakefile
- build/gist
- lib/gist.rb
- vendor/netrc.rb
Git, curl, and other tools already offer support for loading credentials
from ~/.netrc, namely when interacting with GitHub. This uses the netrc
gem to play along. This is implemented as a fallback, in case a token is
not found in the gist-specific file.
Fixes #260.
> Load GitHub token from netrc if it's not in AuthTokenFile

- bin/gist
- lib/gist.rb
fixes #208
Option --skip-empty will skip any zero length files passes to gist. If
all files are empty no gist will be created at all.
test plan:
```
- create two empty files 'empty1' and 'empty2'.
- create a third file with some content 'content1'.
% bin/gist empty1 empty2 content1
% bin/gist --skip-empty empty1 empty2 content1
% bin/gist --skip-empty empty1 empty2
% date | bin/gist
```
> add --skip-empty to skip gisting empty files

- lib/gist.rb
fixes #235
test plan:
- ensure you're signed in (ie. have a token)
% jot 5 | gist
% gist Gemfile
> when gisting stdin default to filename 'a.rb' instead of '-'

- bin/gist
- lib/gist.rb
- spec/rawify_spec.rb
- spec/shorten_spec.rb
- spec/spec_helper.rb
Fixes https://github.com/defunkt/gist/issues/275
This change is needed due to the deprecation warning/removal made by Github on the gist tool. See https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/ for more info.
> Remove anonymous support due to deprecation.

- README.md
- bin/gist
- lib/gist.rb
- spec/rawify_spec.rb
- spec/shorten_spec.rb
Just a few capitalization fixes for "GitHub" and "OAuth2" (along with test updates).
> Fix capitalization of GitHub and OAuth in messages

- README.md
GitHub [no longer supports](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/) anonymous gists.
> README: remove deprecated anonymous features

- README.md
The originally suggested command in the README for manually setting up the `~/.gist` token file does not ensure that the correct file permissions are set on the file, which may expose the token to other user accounts on the system.
I'm changing the documentation to instead suggest running `umask 0077` before creating the file to ensure that no other user accounts on the system will have access to it. In addition, by putting the entire command in parentheses, the command is executed within a subshell so that the umask is only set temporarily for the purposes of creating the file:
```sh
(umask 0077 && echo MY_SECRET_TOKEN > ~/.gist)
```
> README update: Use umask when creating token file

- build/gist
- lib/gist.rb
Instead of through query parameter, since that method is being actively deprecated.
* https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
* https://developer.github.com/v3/#oauth2-token-sent-in-a-header
> Supply access token through Authorization header

- lib/gist.rb
Always pass the authentication token when listing gists. It is needed even when listing public gists on GHE. Moreover, `bin/gist` enforces the presence of the auth token* . 
Here's the output without the auth token (bypassed check in `bin/gist`).
```
$ gist -l username
Traceback (most recent call last):
7: from /usr/local/bin/gist:23:in `<main>'
6: from /usr/local/bin/gist:23:in `load'
5: from /var/lib/gems/2.5.0/gems/gist-5.1.0/bin/gist:167:in `<top (required)>'
4: from /var/lib/gems/2.5.0/gems/gist-5.1.0/lib/gist.rb:213:in `list_all_gists'
3: from /var/lib/gems/2.5.0/gems/gist-5.1.0/lib/gist.rb:269:in `get_gist_pages'
2: from /var/lib/gems/2.5.0/gems/gist-5.1.0/lib/gist.rb:287:in `pretty_gist'
1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse' …
```
> Always pass the auth token when listing all gists

- README.md
Some GitHub Enterprise setups may require the additional `user:email` scope.
Requests fail in a strange way (HTTP 302 Redirect) so it's worth noting here.
Signed-off-by: Lucas Magasweran <lrm@linux.com>
> docs: note the potential requirement for `user:email` scope

- lib/gist.rb
The parsing of the `GITHUB_URL` should support hyphens in host names
to comply with https://tools.ietf.org/html/rfc952 .
Otherwise `gist` will fail to find the corresponding `.gist` token
file if the server contains a hyphen. For example,
`https://github.my-corp.com/`.
Signed-off-by: Lucas Magasweran <lrm@linux.com>
> Allow hyphens in GITHUB_URL

- README.md
- lib/gist.rb
- spec/ghe_spec.rb
The username/password exchange mechanism is (rightfully) deprecated, the
device flow is now in beta, and seems to be the perfect replacement.
This change includes a best-guess of how this might work with GitHub
Enterprise but I haven't tested that, so GitHub Enterprise will continue
to default to the deprecated flow.
Fixes #315
> Use new Oauth flow

- README.md
It appears that the various installation methods currently documented are not more intuitive/convenient/? than using `apt`. Adding it to the instructions so we can document that it has been renamed by Debian to `gist-paste`. 
Hopefully, that will encourage people to use the preferred `gem` installation method.
Fixes #300
> docs: Debian package renamed binary to `gist-paste`
